title: Computing in Context - Ibrahim Alangari
author: Ibrahim Alangari

only_build_toc_files: true

execute:
  execute_notebooks: "off"

sphinx:
 
  config:
    # https://jupyterbook.org/en/stable/interactive/interactive.html#plotly
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.7/require.min.js
    # https://myst-parser.readthedocs.io/en/latest/syntax/cross-referencing.html#implicit-targets
    
    myst_heading_anchors: 4